### ISSUE TITLE
Additional resources

### ISSUE THREAD

**Issue by yassineAlouini** [jeongyoonlee/data-science-process-management#6]
I would like to thank you for this wonderful list. 

I have found these additional resources that you haven't included: 

- https://www.kubeflow.org/ => model deployment/production using a kubernetes cluster.
- https://polyaxon.com/ => similar (to some extent) to the above. Supports more libraries.
- https://algorithmia.com/ => SaaS solution for managing the complete ML workflow cycle.

Thes three could go under the section **Data/Modeling/Deployment Pipelines**. 

Let me know if you want me to create a PR this weekend. Thanks. :)

**Comment by jeongyoonlee** [comment]
I'm so sorry, @yassineAlouini, for getting back to you so late! 

Yes, please create a PR so that I can merge it to master. 

Thanks a lot!

**Comment by yassineAlouini** [comment]
Happy new year. 🎉 
No worries @jeongyoonlee. 😉 
I will do it this weekend and let you know when it is done.

**Comment by jeongyoonlee** [comment]
Merged with #7
